### ISSUE TITLE
Doesn't work with v18 beta on LG webos

### ISSUE THREAD

**Issue by bobbynobble** [mjoshd/hyperhdr-ha#11] opened 2022-04-15 13:38 UTC
I have installed HyperHDR on my LG TV following the guide on the OpenLGTV Discord which works perfectly. This uses a version of HyperHDR called 18.0.0.0beta1 LG webOS compiled by Ambilight FR Discord Community and would like to use your integration with it.

Unfortunately, it looks like your version checking is stopping this...

`Logger: homeassistant.config_entries
Source: custom_components/hyperhdr/__init__.py:154
Integration: HyperHDR ([documentation](https://github.com/awawa-dev/HyperHDR#readme), [issues](https://github.com/mjoshd/hyperhdr-ha/issues))
First occurred: 14:22:30 (1 occurrences)
Last logged: 14:22:30

Error setting up entry 192.168.1.161:19444 for hyperhdr
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 335, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/hyperhdr/__init__.py", line 154, in async_setup_entry
    if AwesomeVersion(version) < AwesomeVersion(HYPERHDR_VERSION_WARN_CUTOFF):
  File "/usr/local/lib/python3.9/site-packages/awesomeversion/awesomeversion.py", line 145, in __lt__
    raise AwesomeVersionCompareException(
awesomeversion.exceptions.AwesomeVersionCompareException: Can't compare <unknown 18.0.0.0beta1 LG webOS compiled by Ambilight FR Discord Community> and <CalVer 17.0.0.0>`

Anything you can do to help?

**Comment by mjoshd** [comment] 2022-04-17 10:07
I'd wager the issue is because the version number being reported has both numbers & letters which makes the comparison fail.

Sounds like you may be using a rooted TV as the source? If so, that is far outside my area of knowledge. I only have experience using various HDMI grabbers like the ezcap320.

Regardless, I don't intend to try chasing down any issues with v18 until it is released as stable.

Closing since v18 is not yet available as a stable release.

**Closed** 2022-04-17 11:07 UTC

**Comment by bobbynobble** [comment] 2022-04-17 11:09
I fixed the problem temporarily by forking this and removing the version checking. You are correct about the naming problem and this has now been fixed by the person who compiled it.
